### ISSUE TITLE
Stop using deprecated GitHub Actions commands

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/pce#52]
There some warnings when our GitHub Actions workflow is run: 

https://github.com/atlanticwave-sdx/pce/actions/runs/3422495265

The warnings are about GitHub's [deprecation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) of some commands.  We use those commands to set up pip cache.

There's probably a better way to set up pip cache, using [setup-python](https://github.com/actions/setup-python) action, like so:

```
steps:
- uses: actions/setup-python@v4
  with:
    python-version: '3.9'
    cache: 'pip' # caching pip dependencies
```
